################################################
#
# application.yml
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#
################################################

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://endpoint/db
    username: username
    password: password

  jpa:
    database: MYSQL
    hibernate:
      show-sql: true
      ##ddl-auto: update
      format_sql: trues
      use_sql_comments: true
      generate_statistics: false
    database-platform: org.hibernate.dialect.MySQLDialect

  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write_dates_as_timestamps: false

management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: /manage
      expose: health
  endpoint:
    shutdown:
      enabled: false

logging:
  level:
    org.springframework: INFO
    root: INFO
